package by.newsportal.news.controller;

public enum CommandName {
    REGISTRATION_PAGE,
    AUTHORIZATION_PAGE,
    REGISTRATION_NEW_USER,
    AUTHORIZATION_USER,
    GO_TO_MAIN_PAGE,
    AFTER_AUTHORIZATION,
    CHANGE_LOCAL,
    ADD_NEWS,
    UNKNOWN_COMMAND
}
